# Generated by Django 2.2.14 on 2020-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_personal_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_statement',
            name='ps_name',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
