# Generated by Django 2.2.14 on 2020-08-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_personal_statement_ps_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_Statement',
        ),
    ]
