# Generated by Django 2.2.14 on 2020-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_personal_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_name', models.CharField(default='abc', max_length=200)),
                ('ps_describe', models.TextField()),
            ],
        ),
    ]
