# Generated by Django 2.2.14 on 2020-08-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_uob_year_1_uob_year_2_uob_year_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uob_year_1',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='uob_year_2',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='uob_year_3',
            old_name='courses',
            new_name='course',
        ),
    ]
