# Generated by Django 2.2.14 on 2020-08-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_mydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(blank=True, max_length=500)),
                ('photo', models.ImageField(upload_to='images/')),
                ('album_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Gallery')),
            ],
        ),
    ]
