# Generated by Django 2.2.14 on 2020-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200813_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
