# Generated by Django 2.2.14 on 2020-08-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200813_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='title',
        ),
    ]
