# Generated by Django 2.2.14 on 2020-08-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200816_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
