# Generated by Django 2.2.14 on 2020-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='compressed_photo',
            field=models.ImageField(default='', upload_to='compressed_images/'),
        ),
    ]
