# Generated by Django 2.2.14 on 2020-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_photos_compressed_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='compressed_photo',
            field=models.ImageField(upload_to='compressed_images/'),
        ),
    ]
