# Generated by Django 2.2.14 on 2020-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200818_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='compressed_photo',
            field=models.ImageField(default='compressed_images/default.jpg', upload_to='compressed_images/'),
        ),
    ]
