# Generated by Django 2.2.14 on 2020-08-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200818_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='compressed_photo',
        ),
    ]
